### ISSUE TITLE
[IMPROVEMENT IDEA] Outbox as Filebased Database

### ISSUE THREAD

**Issue by 3dotsDev** [madslundt/NetCoreMicroservicesSample#10]
Why dont use Filebased Database for Outbox? It can run on the same container and is ultra lightweight. I think of https://www.litedb.org/ or something simillar... what do you think ? The idea is to be nearest as possible to the publishing service and i think you can save one "DB Engine" instance per service ( minimize the possible sources of errors )

**Comment by jbonnett92** [comment]
I'm just curious, so what if you have multiple instances of the same service on different servers? Two service instances pick up the same event and process said event, now if you used the file based one surely you would have a duplicate outbox event right? As the two instances are not close and do not share the outbox database. The whole point of the outbox pattern is to prevent duplicates and stop old data from overriding newer data, processing it in order by queuing it, making sure that the broker doesn't process it multiple times causing data inconsistencies but also providing a fallback if the broker is not available for when it becomes available again. 

You may want to look at this: [https://microservices.io/patterns/data/transactional-outbox.html#result-context](https://microservices.io/patterns/data/transactional-outbox.html#result-context).

Please let me know if you see this still working as I'm a little confused to the suggestion!

**Comment by 3dotsDev** [comment]
ooooh the heck... now i see your point... 
when i write this idea i'm thinking about to minimize the maximum database instances per serviceinstance.... when i correct interpret  your answer then i have only one  outbox instance per servicetype ( event it has multiple service instances )... now then you have 1 database for eventsourcing, 1 for outbox and one for the "queryside"... right ?

thanks for the link... it explains well what the idea behind is....

**Comment by jbonnett92** [comment]
You mean command side right? It's on when changing data... But yes typically 1 db per service (not instance). Though it can be modified to be multiple databases if you wanted to do Z scaling e.g. for a e-commerce, you can have a service instance and database that handles products that start with 'a' and another for products that start with 'b' .etc [https://devcentral.f5.com/s/articles/the-art-of-scale-microservices-the-scale-cube-and-load-balancing](https://devcentral.f5.com/s/articles/the-art-of-scale-microservices-the-scale-cube-and-load-balancing)

Microservices aren't really set in stone in the way that you approach them. You can pick and choose the methodologies to suite the application.

**Comment by 3dotsDev** [comment]
in my previous answer i wrote something wrong... sorry...i meant 1 db for command, 1 db for query and 1 db for outbox per Service... When i start multiple instances from the same service it connecting the same databases.... ok!!! well... the z axis scalling was new to me... thanks  for the link!!!!  thank you for  the answer it brings me further :-)

**Comment by jbonnett92** [comment]
As this is using CQRS there are two databases for what you call "query", it's actually separated into command (write) and query (read), when you make a command it gets stored in a database that then is essentially replicated into the query database which is why it is called eventual consistency.  [https://dzone.com/articles/microservices-with-cqrs-and-event-sourcing](https://dzone.com/articles/microservices-with-cqrs-and-event-sourcing)

It just means that you can always read even at the time of writing to the database, also means that you can scale reads vs writes .etc in this case though, we can't really scale it as it hasn't been adapted to work that way.
