### ISSUE TITLE
API Gateway issue

### ISSUE THREAD

**Issue by jbonnett92** [madslundt/NetCoreMicroservicesSample#3]
Hi,
The API Gateway keeps failing...
<img width="1122" alt="Screenshot 2020-08-31 at 07 13 27" src="https://user-images.githubusercontent.com/3740700/91688364-b5a00000-eb59-11ea-95f1-c3045d9c88c7.png">

It appears that it isn't able to discover the Consul service.
Any ideas what the issue is?

Thanks,
Jamie

**Comment by jbonnett92** [comment]
I think there could be a couple of issues.

Here [https://github.com/madslundt/NetCoreMicroservicesSample#consul](https://github.com/madslundt/NetCoreMicroservicesSample#consul) you mention that the API Gateway uses Consul, though in the appsettings.json there is no Consul options.

I also noticed that there is no configure method, there is no `app.UseConsul()`.

**Comment by madslundt** [comment]
Thank you for reporting this. 

I'm looking to replace the api gateway with something that also integrates better with Swagger

**Comment by jbonnett92** [comment]
Anything in particular that you are looking at so far?

**Comment by madslundt** [comment]
Normally I'd go with a fully managed API gateway on AWS, Azure, etc.
Right now I'm looking at Kong and Tyk

**Comment by jbonnett92** [comment]
Not sure if you're looking for others opinions, but I for sure would prefer Ocelot as it is completely free and you can implement anything with it rather than using paid plugins .etc

**Comment by madslundt** [comment]
You are absolutely right.
I started looking into Kong and Tyk and realized they offer a community edition (free) and a premium version (paid).

I'll look into improving the Api gateway with Ocelot.
