### ISSUE TITLE
Outbox and EventStore switch to Efcore Issues

### ISSUE THREAD

**Issue by mkojoa** [madslundt/NetCoreMicroservicesSample#5]
With the Outbox and EventStore setup in the appsettings, when i change the type from mogo to ef, all the service keeps failing. After debugging through i realized that the dbContextOption appears **null** in both the **EventStoresExtensions** and **OutboxExtensions**.
![ef_error](https://user-images.githubusercontent.com/20341997/92220370-6f191100-ee8b-11ea-81cb-0ebea2f97cb6.png)

**Comment by madslundt** [comment]
The documentation has not been updated for this yet.

You need to pass in DbContextOptionsBuilder for it to know which database plugin it should use.
Just as you do when you're adding the DataModel.

**Comment by mkojoa** [comment]
Well noted sir.
