### ISSUE TITLE
How does an event get transmitted across process boundaries?

### ISSUE THREAD

**Issue by CasperWSchmidt** [madslundt/NetCoreMicroservicesSample#9]
Perhaps I just haven't looked good enough, but as far as I can see, the Outbox and the EventStore writes to a database, then an eventlistener is called, but how is one service able to notify another service (which runs completely separate)? I can see that one can choose to use RabbitMQ, but isn't that in-memory/in-process as well?

**Comment by madslundt** [comment]
Hi Casper,

Yes, it's correct that the service can be set up to use Outbox and/or EventStore.

Both Outbox and EventStore are only used by the service.
Outbox is used to store outgoing events (temporary store while the event has not been published yet).
EventStore is used to store all states that have ever happened in the application.

RabbitMQ is not in-memory. RabbitMQ is a message broker that can be used for a distributed system.
From RabbitMQ "RabbitMQ can be deployed in distributed and federated configurations to meet high-scale, high-availability requirements."

I'm working on improving this repo by using some other patterns for handling error states.
